# Generated by Django 5.1.7 on 2026-08-03 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_ai", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userarchitecture",
            constraint=models.UniqueConstraint(
                fields=("user", "original"), name="one_copy_per_user"
            ),
        ),
    ]
