# Generated by Django 5.1.7 on 2026-08-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_ai", "0002_userarchitecture_one_copy_per_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userarchitecture",
            name="one_copy_per_user",
        ),
    ]
