# Generated by Django 5.1.7 on 2026-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_ai", "0004_technologycategory_technology"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(unique=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("select", "Select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("required", models.BooleanField(default=True)),
            ],
        ),
    ]
