# Generated by Django 5.1.7 on 2026-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("architecture_ai", "0005_projectfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectfield",
            name="order",
        ),
    ]
