# Generated by Django 6.1 on 2026-08-24 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ai', '0006_remove_projectfield_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('indexed_at', models.DateTimeField(auto_now=True)),
                ('architecture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='architecture_ai.architecture')),
            ],
        ),
    ]
