# Generated by Django 6.1 on 2026-08-25 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture_ai', '0007_architectureembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='architecture_ai.architecture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
