services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ollama
      - redis

  redis:
    image: redis:7-alpine
    container_name: kernx_redis
    restart: unless-stopped

  celery:
    build: .
    container_name: kernx_celery
    command: celery -A kernx worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: