# Generated by Django 5.1.7 on 2026-08-20 13:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Course", "Course"),
                            ("E-book", "E-book"),
                            ("Cheatsheet", "Cheatsheet"),
                            ("Quick-Guide", "Quick-Guide"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Description"),
                ),
                ("img", models.ImageField(upload_to="media")),
                ("rating", models.FloatField(default=None)),
            ],
        ),
    ]
