# Generated by Django 6.1 on 2026-08-20 15:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='digital_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_of', models.CharField(choices=[('Course', 'Course'), ('E_book', 'E_book'), ('Cheatsheet', 'Cheatsheet'), ('Quick_Guide', 'Quick_Guide')], max_length=50)),
                ('price', models.FloatField()),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('img', models.ImageField(upload_to='media')),
                ('rating', models.FloatField(default=None)),
                ('duration', models.DurationField(default=None)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
