# Generated by Django 6.1 on 2026-08-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_digital_products_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_products',
            name='link',
            field=models.URLField(default='None'),
        ),
    ]
